/*
 * Day 08 — Generic Repository Pattern + EF Core Operations
 *
 * Problem:
 * Write a generic repository interface and implement it for Vendor using EF Core.
 * Understand the core EF Core CRUD operations.
 *
 * This is a LEARNING problem — not the actual repository structure in the project.
 * The project uses specific interfaces (IVendorRepository, IInstrumentRepository)
 * not a generic IRepository<T, TKey>.
 */

// ─────────────────────────────────────────────
// Generic Interface
// ─────────────────────────────────────────────

public interface IRepository<T, TKey> where T : class
{
    Task<T?> GetByIdAsync(TKey id, CancellationToken ct = default);
    Task<ICollection<T>> GetAllAsync(CancellationToken ct = default);
    Task<TKey> AddAsync(T entity, CancellationToken ct = default);
    Task UpdateAsync(T entity, CancellationToken ct = default);
}

// where T : class — generic constraint.
// Tells the compiler T must be a reference type (class), not a value type (int, struct).
// Required because EF Core's Set<T>() only works with reference types.
// TKey has no constraint — it can be int, Guid, string etc.

// ─────────────────────────────────────────────
// Implementation for Vendor
// ─────────────────────────────────────────────

public class VendorRepository : IRepository<Vendor, int>
{
    private readonly CatalogueDbContext _context;

    public VendorRepository(CatalogueDbContext context)
    {
        _context = context;
    }

    public async Task<Vendor?> GetByIdAsync(int vendorId, CancellationToken ct = default)
    {
        // FindAsync — searches by configured primary key (HasKey in config)
        // Checks EF Core change tracker first — no DB hit if already loaded this request
        // Returns null if not found — no exception
        return await _context.Set<Vendor>().FindAsync(new object[] { vendorId }, ct);
    }

    public async Task<ICollection<Vendor>> GetAllAsync(CancellationToken ct = default)
    {
        // ToListAsync — executes SELECT * FROM vendors
        // Always async — hits the database
        return await _context.Set<Vendor>().ToListAsync(ct);
    }

    public async Task<int> AddAsync(Vendor vendorEntity, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(vendorEntity);

        // AddAsync — starts tracking the entity in Added state
        // Does NOT hit the database yet
        await _context.AddAsync(vendorEntity, ct);

        // SaveChangesAsync — generates INSERT SQL and executes it
        // After this, VendorId is populated by EF Core with the DB-generated value
        await _context.SaveChangesAsync(ct);

        // Return the PK that was generated by the DB
        return vendorEntity.VendorId;
    }

    public async Task UpdateAsync(Vendor vendorEntity, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(vendorEntity);

        // Update — synchronous. Marks entity as Modified in the change tracker.
        // Does NOT hit the database. No async version exists because
        // it's just an in-memory state change — no IO involved.
        _context.Update(vendorEntity);

        // SaveChangesAsync — generates UPDATE SQL and executes it
        await _context.SaveChangesAsync(ct);
    }
}

/*
 * ─────────────────────────────────────────────
 * Why Update() is synchronous but SaveChangesAsync() is async
 * ─────────────────────────────────────────────
 *
 * EF Core has a two-step process for writes:
 *
 * Step 1 — Change tracking (in-memory, synchronous):
 *   _context.Add(entity)    → marks entity as Added
 *   _context.Update(entity) → marks entity as Modified
 *   _context.Remove(entity) → marks entity as Deleted
 *   No database involved — just updating an in-memory dictionary
 *   No IO = no need for async
 *
 * Step 2 — Persistence (hits the database, async):
 *   await _context.SaveChangesAsync() → generates SQL, sends to DB, waits for response
 *   IO involved = async
 *
 * The rule: async is for IO operations. In-memory operations are synchronous.
 *
 * ─────────────────────────────────────────────
 * Set<T>() vs named DbSet property
 * ─────────────────────────────────────────────
 *
 * Both are equivalent:
 *   _context.Set<Vendor>()  → generic, works in generic classes where T is a type param
 *   _context.Vendors        → named property, only works when you know the specific type
 *
 * In a generic class (IRepository<T, TKey>) you MUST use Set<T>()
 * because the compiler doesn't know what T is at compile time.
 *
 * In a specific repository (VendorRepository) either works.
 * Named property (_context.Vendors) is more readable.
 *
 * ─────────────────────────────────────────────
 * FindAsync vs FirstOrDefaultAsync
 * ─────────────────────────────────────────────
 *
 * FindAsync(id):
 *   - Searches by configured primary key only
 *   - Checks change tracker cache first — no DB hit if already loaded
 *   - Slightly faster for PK lookups
 *   - No lambda needed
 *
 * FirstOrDefaultAsync(x => x.Id == id):
 *   - Always hits the database
 *   - Can search by any column
 *   - More flexible
 *
 * For PK lookups — use FindAsync. For anything else — use FirstOrDefaultAsync.
 *
 * ─────────────────────────────────────────────
 * Why we did NOT use generic IRepository<T, TKey> in the actual project
 * ─────────────────────────────────────────────
 *
 * The generic repository pattern is a common pattern but has real limitations:
 *
 * 1. Domain-specific methods don't fit.
 *    IInstrumentRepository has ResolveBySymbolAsync, GetSnapshotAsync, SearchAsync.
 *    None of these belong in a generic interface.
 *
 * 2. Different PKs per entity.
 *    Vendor = int PK. Instrument = Guid PK. SymbolXRef = Guid PK.
 *    A generic interface handles this via TKey but it gets awkward.
 *
 * 3. Abstraction for abstraction's sake.
 *    The generic pattern adds a layer without adding real value when
 *    every repository has unique methods anyway.
 *
 * 4. Testing is not simpler.
 *    You still mock the specific interface in tests.
 *    The generic layer adds nothing to testability.
 *
 * The project uses specific interfaces because each repository
 * has a focused contract that matches its domain. That's better design.
 *
 * Generic repository is good to understand (which is why we practiced it)
 * but not always the right choice to implement.
 *
 * ─────────────────────────────────────────────
 * When TO use generic repository
 * ─────────────────────────────────────────────
 *
 * Good fit when:
 * - All entities share the same operations (pure CRUD, no domain logic)
 * - Building a generic admin panel or scaffolding tool
 * - Early stage project where you want to move fast
 *
 * Not a good fit when:
 * - Entities have domain-specific query needs (my case)
 * - Different PKs and relationships
 * - Complex filtering and pagination per entity
 */
